on: [push, pull_request]

jobs:
  template-sync:
    runs-on: ubuntu-latest

    steps:
      name: Template Repository Sync
      uses: ahmadnassri/action-template-repository-sync@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: true
-
